Rename to Illumina Annotator
Illumina/NirvanaDocumentation pull request #39
Opened 2023-10-19 19:37 UTC by Fahd-Siddiqui

2023-10-19 19:37 UTC, Fahd-Siddiqui commented
![image](https://github.com/Illumina/NirvanaDocumentation/assets/25212271/b6fa027c-52c3-4f6b-adcc-8f6f1017d7ee)

2023-10-19 19:42 UTC, rajatshuvro commented
The Logo should not go past the Left panel. And it also looks too large on the main panel.

2023-10-19 19:45 UTC, Fahd-Siddiqui commented
> The Logo should not go past the Left panel. And it also looks too large on the main panel.

Agree, the logo you provided was looking really weird. 

On your second point, agreed. I am going to fix it.

2023-10-19 22:06 UTC, rajatshuvro commented on docs/introduction/TestIlluminaAnnotator.sh
> +ILLUMINA_ANNOTATOR_BIN=$ILLUMINA_ANNOTATOR_BUILD_DIR/IlluminaAnnotator.dll
Let's use Annotator.dll

2023-10-19 22:07 UTC, rajatshuvro commented on docs/introduction/covid19.md
> +dotnet IlluminaAnnotator.dll \
Let's use Annotator.dll

2023-10-19 22:07 UTC, rajatshuvro commented on docs/introduction/getting-started.md
> +dotnet IlluminaAnnotator.dll \
Let's use Annotator.dll

2023-10-19 22:07 UTC, rajatshuvro commented on docs/introduction/getting-started.md
> +USAGE: dotnet IlluminaAnnotator.dll -i <vcf path> -c <cache dir> --sd <sa dir> -r <ref path> -o <base output filename>
Let's use Annotator.dll

2023-10-19 22:07 UTC, rajatshuvro commented on docs/introduction/getting-started.md
> +dotnet IlluminaAnnotator.dll \
Let's use Annotator.dll

2023-10-19 22:08 UTC, rajatshuvro requested changes
Let's use Annotator.dll

2023-10-19 22:12 UTC, rajatshuvro commented
I see the local url says "NirvanaDocumentation"

2023-10-20 17:24 UTC, rajatshuvro approved these changes

2023-10-20 17:25 UTC, merged